# Generated by Django 5.1.15 on 2026-04-07 09:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('website', models.URLField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('spirit', 'Spirit'), ('liqueur', 'Liqueur'), ('wine', 'Wine / Vermouth'), ('beer', 'Beer / Cider'), ('mixer', 'Mixer / Soda'), ('juice', 'Juice'), ('syrup', 'Syrup / Sweetener'), ('bitter', 'Bitters'), ('garnish', 'Garnish'), ('dairy', 'Dairy / Egg'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('abv', models.DecimalField(blank=True, decimal_places=1, help_text='Alcohol by volume (%)', max_digits=4, null=True)),
                ('image', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(help_text='Short intro shown in cards and search results')),
                ('instructions', models.TextField(help_text='Step-by-step preparation instructions')),
                ('history', models.TextField(blank=True, help_text='Origin story behind the cocktail')),
                ('image', models.URLField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=10)),
                ('glass_type', models.CharField(choices=[('coupe', 'Coupe'), ('rocks', 'Rocks / Old Fashioned'), ('highball', 'Highball / Collins'), ('martini', 'Martini'), ('flute', 'Champagne Flute'), ('tiki', 'Tiki Mug'), ('hurricane', 'Hurricane'), ('copper', 'Copper Mug'), ('wine', 'Wine Glass'), ('shot', 'Shot Glass'), ('snifter', 'Snifter'), ('other', 'Other')], default='rocks', max_length=20)),
                ('prep_time_minutes', models.PositiveSmallIntegerField(default=5, help_text='Estimated preparation time in minutes')),
                ('is_alcoholic', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the homepage')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='cocktails.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cocktails.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, help_text='e.g. 2, 1.5, 1/2', max_length=20)),
                ('unit', models.CharField(blank=True, choices=[('oz', 'oz'), ('ml', 'ml'), ('cl', 'cl'), ('dash', 'dash(es)'), ('drop', 'drop(s)'), ('tsp', 'teaspoon(s)'), ('tbsp', 'tablespoon(s)'), ('cup', 'cup(s)'), ('piece', 'piece(s)'), ('slice', 'slice(s)'), ('sprig', 'sprig(s)'), ('wedge', 'wedge(s)'), ('whole', 'whole'), ('barspoon', 'barspoon(s)'), ('rinse', 'rinse'), ('top', 'top off'), ('to_taste', 'to taste')], max_length=20)),
                ('notes', models.CharField(blank=True, help_text="e.g. 'freshly squeezed', 'chilled'", max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_uses', to='cocktails.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='cocktails.recipe')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='cocktails.RecipeIngredient', to='cocktails.ingredient'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cocktails.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('recipe', 'user')},
            },
        ),
    ]
