# Generated by Django 5.1.15 on 2026-04-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_alter_bar_image_alter_ingredient_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientExternalRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=64)),
                ('external_id', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_refs', to='cocktails.ingredient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_key', 'external_id'), name='cocktails_ingredientexternalref_source_id_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RecipeExternalRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, help_text='Stable key for the importer (e.g. thecocktaildb).', max_length=64)),
                ('external_id', models.CharField(help_text='Primary id in the external catalog.', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_refs', to='cocktails.recipe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_key', 'external_id'), name='cocktails_recipeexternalref_source_id_uniq')],
            },
        ),
    ]
