# Generated by Django 5.1.15 on 2026-04-21 10:04

import cocktails.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_recipe_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='recipefavorite',
            new_name='cocktails_r_user_id_f33ae1_idx',
            old_name='cocktails_r_user_id_fcaad5_idx',
        ),
        migrations.RenameIndex(
            model_name='recipefavorite',
            new_name='cocktails_r_user_id_499a2d_idx',
            old_name='cocktails_r_user_id_6e7d01_idx',
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=False, help_text='When True, member recipe could appear in vault (reserved for future use).'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(choices=[('catalog', 'Catalog'), ('member', 'Member')], db_index=True, default='catalog', help_text='Catalog recipes appear in Recipe Vault; member recipes are personal until public.', max_length=10),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5')), cocktails.validators.validate_half_star_rating]),
        ),
        migrations.AddField(
            model_name='recipewishlist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='cocktails.recipe'),
        ),
        migrations.AddField(
            model_name='recipewishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recipewishlist',
            index=models.Index(fields=['user', 'recipe'], name='cocktails_r_user_id_52e56f_idx'),
        ),
        migrations.AddIndex(
            model_name='recipewishlist',
            index=models.Index(fields=['user', '-created_at'], name='cocktails_r_user_id_bc13d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipewishlist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='cocktails_recipewishlist_user_recipe_uniq'),
        ),
    ]
