# Generated by Django 5.1.15 on 2026-04-21 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_member_wishlist_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCabinetIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_memberships', to='cocktails.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_ingredients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'ingredient'], name='cocktails_u_user_id_053fe5_idx'), models.Index(fields=['user', '-created_at'], name='cocktails_u_user_id_992ff3_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'ingredient'), name='cocktails_usercabinet_user_ingredient_uniq')],
            },
        ),
    ]
